### ISSUE TITLE
Estimated release date

### ISSUE THREAD

**Issue by ofir5300** [grafana/google-bigquery-datasource#117]
Hello dear Grafana engineers 👋 
I am Ofir the maintainer of [doitintl/bigquery-grafana](https://github.com/doitintl/bigquery-grafana)

I was wondering if you might supply an estimated time frame until your BigQuery data source will come alive?
Tnx

CC [dprokop](https://github.com/dprokop)

**Comment by Elyahou** [comment]
@ofir5300 It is already live and ready to use: https://grafana.com/grafana/plugins/grafana-bigquery-datasource/

**Comment by ofir5300** [comment]
Oh wow, that makes all piece of extra work on [doitintl/bigquery-grafana](https://github.com/doitintl/bigquery-grafana) redundant isnt it?

**Comment by dprokop** [comment]
@ofir5300 we are more than happy to welcome contributions from your end and resume the conversation we started a few months back.
