### ISSUE TITLE
FEATURE REQUEST: $__timeShifting(1m) -> compare data from the current range to the previous range

### ISSUE THREAD

**Issue by joelsdc** [grafana/google-bigquery-datasource#118]
Hi, 

I've been using the DoIT Grafana Datasource but they have recently announced they have retired the plugin and suggested to move to the Grafana official one:

_...
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.
..._

I'm not sure of the amount of work required, but would it be possible for you guys to port the `$__timeShifting()` macro?

It allows to do things like:

```
SELECT
  $__timeGroup(timestamp, $interval),
  COUNT(DISTINCT some_value) AS something
FROM `someschema.sometable`
WHERE
  $__timeShifting(1w) AND
  condition1 AND
  condition2 ...
GROUP BY time
ORDER BY time DESC
```

And output from a test environment:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/16212586/168201911-4379e800-d603-4805-b241-1f2128024187.png">

More info: https://github.com/doitintl/bigquery-grafana/blob/fb4b6ea6a6543ba72b5b5e1878f7416418431841/src/datasource.ts#L102

Thanks!

**Comment by joelsdc** [comment]
I just noticed this:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/16212586/168208024-8644c8e6-b08d-4798-9d5a-9e5b6338040e.png">

So then my question is, why does the `$__timeShifting(1w)` not work? 

When I try to use it I get this error:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/16212586/168208160-3aea9c64-56c9-4119-809a-b8499d290bd9.png">

**Comment by dprokop** [comment]
@joelsdc thank you for opening the issue! Indeed, our plugin is forked from the community plugin, yet it's a complete rewrite of it. Hence, time-shifting doesn't work. That's an intentional change as we want to implement the time-shifting in Grafana core so that all plugins can benefit from this feature. I'll keep you posted when we have this in place in Grafana.

**Comment by gabor** [comment]
hi, this is still planned to be solved in core grafana, so i think we can close this issue
( there are several github-issues mentioning this in core grafana, you may want to subscribe to those to be updated about this, for example: https://github.com/grafana/grafana/issues/22942 and https://github.com/grafana/grafana/issues/82093)
