### ISSUE TITLE
raw editor no longer visible, plugin version 1.1.0

### ISSUE THREAD

**Issue by jermudgeon** [grafana/google-bigquery-datasource#120]
On a particular dashboard (not universally), I can no longer edit a raw query: 
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/8975763/169160736-e5ba3ab0-37ba-40fe-85fe-331698d4ccaf.png">
This happens on any instance of the BQ plugin on this particular dashboard. Clearing local cache does not help.

Grafana v8.3.3

**Comment by jermudgeon** [comment]
Correction, this error is appearing on multiple dashboards.

**Comment by jermudgeon** [comment]
A hard reload appears to have fixed it for now.

**Comment by dprokop** [comment]
@jermudgeon Looking at your screenshot it seems like you are trying to use https://github.com/doitintl/bigquery-grafana/.
