### ISSUE TITLE
How to migrate from doitintl plugin

### ISSUE THREAD

**Issue by TaylorMutch** [grafana/google-bigquery-datasource#125]
I've failed to find docs for this so opening an issue.

Is there any guide or plan for a guide on how to migrate from [the old plugin](https://github.com/doitintl/bigquery-grafana) to this one?

**Comment by zoltanbedi** [comment]
Hi @TaylorMutch,

From Grafana version 8.5 we support importing queries which means that when you change from the old plugin to this new plugin it will import your query and you will be able to use it so there is no need for migration. Please keep in mind that this will only import your **raw** query.

We can definitely mention this in the readme. If you can open a PR mentioning this in the readme would be helpful.

**Comment by dprokop** [comment]
It's now added to the README: https://github.com/grafana/google-bigquery-datasource#importing-queries-created-with-doit-international-bigquery-datasource-plugin
