### ISSUE TITLE
VQB: Support column selection for time

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/google-bigquery-datasource#126]
In the old plugin you could select the column which would then be used as the time field for the time series visualisation. See time column in the screenshot.

<img width="1552" alt="Screenshot 2022-05-31 at 10 45 09" src="https://user-images.githubusercontent.com/13729989/171132173-04bf27a5-9a40-48a1-a830-ae095d138160.png">

**Comment by dprokop** [comment]
Few things we discussed two weeks ago:

1. We are not sure this is an actual issue or just a assumption that the complaints will come if we don't add id.
2. We want to preselect the time column in the Columns section of the VQB, only if the format is selected to be a time series.
3. For the metric column - I understand the consensus is we will not bring it back.

This work should be handled during the SQL-ish data sources migration (cc @zoltanbedi @scottlepp). I'm closing this issue as it's not relevant to BQ only and should be solved across data sources using this new query builder.
