### ISSUE TITLE
Error: Plugin Unavailable while doing save and test when creating a data source

### ISSUE THREAD

**Issue by yash-nigam-db** [grafana/google-bigquery-datasource#130]
Grafana used : grafana-enterprise-9.0.0-1.x86_64.rpm
Downloaded and extracted plugin: grafana-bigquery-datasource-1.1.1.linux_amd64.tar.gz inside /var/lib/grafana/plugins folder
Gave permission grafana:grafana to /var/lib/grafana/plugins folder.

Restarted grafana using systemctl stop, start
Opened UI - inside server admin - plugins - Google Big Query plugin can be seen as signed and installed

Grafana Labs
[Website](https://github.com/grafana/google-bigquery-datasource/)
1.1.1
[Signed](https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/)
Level:  Grafana Labs
Signed by: Grafana Labs

Added new datasource, 
clicked on Save and Test, shows Datasource Updated, but Error Plugin available.

Logs from /var/log/grafana/grafana.log

logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-06-17T10:12:25.444477016Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.165.120.46 time_ms=0 duration=776.226µs size=27 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-06-17T10:12:28.956928811Z level=error msg="Plugin unavailable" error="plugin unavailable" remote_addr=10.168.149.191 traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-06-17T10:12:28.957039627Z level=error msg="Request Completed" method=GET path=/api/datasources/6/health status=503 remote_addr=10.168.149.191 time_ms=2 duration=2.197526ms size=77 referer=http://100.88.125.147:3000/datasources/edit/iPZ0duCnk traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-06-17T10:12:29.720980499Z level=error msg="Plugin unavailable" error="plugin unavailable" traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-06-17T10:12:29.721093604Z level=error msg="Request Completed" method=POST path=/api/datasources/6/resources/defaultProjects status=503 remote_addr=10.168.149.191 time_ms=6 duration=6.394733ms size=78 referer=http://100.88.125.147:3000/datasources/edit/iPZ0duCnk traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-06-17T10:12:43.449811751Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.165.120.46 time_ms=0 duration=760.307µs size=27 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-06-17T10:12:47.042616643Z level=info msg="Request Completed" method=GET path=/api/ruler/grafana/api/v1/rules status=401 remote_addr=10.165.120.46 time_ms=1 duration=1.057913ms size=27 referer=http://100.88.125.147:3000/alerting/list traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-06-17T10:12:47.042907561Z level=info msg="Request Completed" method=GET path=/api/prometheus/grafana/api/v1/rules status=401 remote_addr=10.165.120.46 time_ms=1 duration=1.358999ms size=27 referer=http://100.88.125.147:3000/alerting/list traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-06-17T10:12:58.448535253Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.165.120.46 time_ms=0 duration=756.009µs size=27 referer= traceID=00000000000000000000000000000000

**Comment by zoltanbedi** [comment]
I tried recreate this and it is not working in mac as well.
However I can see an error in grafana log as well ERROR[06-17|15:08:18] Could not start plugin                   logger=plugin.manager pluginId=grafana-bigquery-datasource err="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."

Can you try to install the plugin with grafana-cli or from the plugin catalog?

**Comment by yash-nigam-db** [comment]
Hello @zoltanbedi 
The compute instance on which i am trying this, does not have internet connectivity, so i need to download the big query plugin first on this instance and then extract it.

I checked grafana-cli  documentation https://grafana.com/docs/grafana/next/cli/ but could not find any option to install a plugin using a downloaded plugin zip file.

**Comment by dprokop** [comment]
@yash-nigam-db it's described in Grafana dockumentation: https://grafana.com/docs/grafana/latest/administration/plugin-management/#install-a-plugin:~:text=Install%20a%20packaged%20plugin

**Comment by dprokop** [comment]
Ah sorry for prematurely closing this issue!

**Comment by gabor** [comment]
hi, as we got no response to our last message for a long time, i assume this is not actual anymore, and close the issue. if this is not solved yet, just reply please, and we can reopen the issue.thanks!
