### ISSUE TITLE
Lack of job informations in GCP

### ISSUE THREAD

**Issue by test-graf** [grafana/google-bigquery-datasource#134]
Hello

Grafana version : Grafana v8.5.9 (2955d0bc8a)
Google BigQuery plugin version : 1.2.0

It seems that when this new connector uses the API, there is something wrong about the way the job is configured. In the GCP console we are able to see the list of queries done at the project level but with this new connector it does not work anymore, see attached picture
![image](https://user-images.githubusercontent.com/109796590/180415841-2c12d24d-d3e7-4397-8371-c9434eacbdd1.png)

And this is what we have with the old DoIT connector : 
![image](https://user-images.githubusercontent.com/109796590/180416050-1f110542-7afa-4f27-a852-de473082da16.png)

Let me know if i can provide further information. 
thanks

**Comment by zoltanbedi** [comment]
I've checked with our test instance and it looks good to me. Can you please help me with more details or how could I reproduce this?
![Screenshot 2022-08-01 at 12 53 32](https://user-images.githubusercontent.com/13729989/182133227-57f1f679-5cb4-47c6-a8cf-a099eba5573f.png)

**Comment by test-graf** [comment]
Hello Zoltan
Indeed you're right, I was missing some permissions : 
- bigquery.jobs.listExecutionMetadata
- bigquery.jobs.listAll

**Comment by zoltanbedi** [comment]
Thank you for confirming @test-graf!
