### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by test-graf** [grafana/google-bigquery-datasource#135]
Hello

Grafana version : Grafana v8.5.9 (2955d0bc8a)
Google BigQuery plugin version : 1.2.0

It seems like the grafana call ignores the location and puts by default "US" as the location for the datasets. See attached picture : 
![image](https://user-images.githubusercontent.com/109796590/180451812-2b76a3ec-ce1c-457b-8245-7ec67d1c7c74.png)

When doing this request from the GCP console, there is no error raised : 
![image](https://user-images.githubusercontent.com/109796590/183450101-0759fc46-96b1-4200-8a59-35c9bfeda483.png)

**Comment by zoltanbedi** [comment]
Thanks for opening this issue @test-graf. I was able to reproduce this.

**Comment by dprokop** [comment]
@test-graf we are investigating this issue. We'll get back to you as soon as we find out the root cause which seems to live outside of the data source.

**Comment by dprokop** [comment]
@test-graf the fix is now release in v1.2.1, I think it should solve your problem.

**Comment by test-graf** [comment]
Great, thanks!
