### ISSUE TITLE
timeFilter macro does not work in variable query

### ISSUE THREAD

**Issue by tkinz27** [grafana/google-bigquery-datasource#137]
Not sure if this is an issue with this plugin or grafana directly but it seems like if I try to use `$__timeFilter` in a variable query the query editor always says I will return 0 results and I never do get any results.

There is no query inspector, but I would guess that the query is being expanded to be an interval between two identical timestamps. I am trying to give people the ability to select a filter that would actually show some data for the current time range. 

![image](https://user-images.githubusercontent.com/3259664/181590930-ec8580cc-5ef8-4757-9993-4f536c650043.png)

**Comment by tkinz27** [comment]
So I just got frustrated and looked into this a bit more. I can see in the network tab that variables get expanded before sent to the backend, but the macros do not. I was able to replace `$__timeFilter(sampleTIme)` with `sampleTime > TIMESTAMP_MILLIS(${__from})` and that works. So for me that work around can work.

**Comment by zoltanbedi** [comment]
good news this is fixed in 1.2.8!
