### ISSUE TITLE
"BigQuery plugin failed" on iOS devices

### ISSUE THREAD

**Issue by tomwilkie** [grafana/google-bigquery-datasource#138]
I have a dashboard that uses the BigQuery datasource - works perfectly on Chrome on a Mac, but fails to load with the following error on Safari on iOS:

![image](https://user-images.githubusercontent.com/444037/182133660-e21ab0cf-148a-43a6-bdf8-b3336e1a730d.png)

**Comment by chs820** [comment]
It looks like that's the old dointl data source. We've seen that bug come up in the past, but it should be remedied with the new Grafana one.

As an aside, I'm not sure who has permissions to do so, but we should probably rename the old data source to call out that it's deprecated

**Comment by zoltanbedi** [comment]
@chs820 you are right. I'm going to go ahead and add deprecated to the title before we remove those datasources. We added the same datasources but with this plugin. Those start with the NEW keyword. @tomwilkie what you can do is change the datasource to the one that start with NEW.
