### ISSUE TITLE
Fetch error: 404 Instantiating https://.../public/plugins/grafana-bigquery-datasource/module.js

### ISSUE THREAD

**Issue by pxn83q5** [grafana/google-bigquery-datasource#146]
grafana used : grafanaoss:9.1.0 running in GCP Kubernetes.  

we are seeing below error when trying to install bigquery datasource from the UI as a server admin. 

Error : 
"Fetch error: 404 Instantiating https://.../public/plugins/grafana-bigquery-datasource/module.js Loading plugins/grafana-bigquery-datasource/module"

**Comment by zoltanbedi** [comment]
Hi @pxn83q5,

Thanks for opening this issue. Can you please check if you can install any other plugin through the ui?

**Comment by zoltanbedi** [comment]
I'm going to close this issue as there was no response.
