### ISSUE TITLE
"Processing location" to allow variable

### ISSUE THREAD

**Issue by MikeLin2018** [grafana/google-bigquery-datasource#148]
Hello,

Grafana version : Grafana v8.3.4 (a551d74b11)
Google BigQuery plugin version : 1.2.1

It seems like the Google BigQuery plugin is unable to replace variable in "Processing location". See attached picture:
<img width="996" alt="image" src="https://user-images.githubusercontent.com/39137700/194968438-f11ea06e-53d5-4a0c-873a-d4d667f3f03d.png">

Support for variable replacement in "Processing location" would be great for dashboard that use dataset as variable and query different BQ location based on a Grafana variable.

**Comment by zoltanbedi** [comment]
While we didn't add variable support for the location we added a new option to select automatic location. This would solve your problem as well. Expect it in the new release soon.

**Comment by jenishjain** [comment]
@MikeLin2018 @zoltanbedi was this fixed, also do we have any work around for this in the older versions?
tried fixing the location using the SET @@location syntax but that isn't helping either

**Comment by zoltanbedi** [comment]
This was fixed by adding the automatic location option. There is no workaround afaik because I think there were some backend changes. @jenishjain
