### ISSUE TITLE
$__timeGroup not working with joins

### ISSUE THREAD

**Issue by HaddadJoe** [grafana/google-bigquery-datasource#153]
$__timeGroup macro is replacing the name of the column with quotes [here](https://github.com/grafana/google-bigquery-datasource/blob/main/pkg/bigquery/macros.go#L41). This is causing some issues on queries that require table name specification before the column, very common pattern when joining tables.

For example, using `a_ts` as an alias for our table inside the `$__timeGroup` fails
This query works
```
SELECT
  $__timeGroup(created, 1d),
  action as metric,
  COUNT(a_ts.id) AS value
FROM
  table_name a_ts
GROUP BY 1,2
ORDER BY 1, 3 desc
limit 10
```
This query does not work and fail with message  `Unrecognized name: `a_ts.created` at [2:38], invalidQuery`

```
SELECT
  $__timeGroup(a_ts.created, 1d),
  action as metric,
  COUNT(a_ts.id) AS value
FROM
  table_name a_ts
GROUP BY 1,2
ORDER BY 1, 3 desc
limit 10
```

Naming the table is important in case joining tables and having ambiguous column names for example queries like 
```
SELECT
  $__timeGroup(a_ts.created, 1d), # we need to have a_ts before created at since this column is present in both tables
  action as metric,
  COUNT(a_ts.id) AS value
FROM
  table_1 a_ts
  LEFT JOIN table_2 ts ON ts.id = a_ts.monitor_id
GROUP BY 1,2
ORDER BY 1, 3 desc
limit 10
```

**Comment by HaddadJoe** [comment]
@zoltanbedi any updates on the following? It really renders the plugin unusable on basic time grouping queries.

**Comment by zoltanbedi** [comment]
Hi @HaddadJoe,
the error message you are seeing here is from BigQuery can you please show me how the sql statement should look with alias that works on BigQuery but not in Grafana?

**Comment by HaddadJoe** [comment]
yes of course, here's how grafana plugin is translating this into BQ's query syntax

```
SELECT
  TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`a_ts.created`), 86400) * 86400),
  COUNT(a_ts.id) AS value,
  action as metric
FROM table_1 a_ts
LEFT JOIN table_2 ts ON ts.id = a_ts.monitor_id
GROUP BY time, action
ORDER BY time
LIMIT 10
```
As mentioned above, this returns `Unrecognized name: `a_ts.created` at [2:38]` and yes this is definitely coming from bq because the grafana plugin is building the query wrongly [here](https://github.com/grafana/google-bigquery-datasource/blob/main/pkg/bigquery/macros.go#L41).

Query should look like 
```
SELECT
  TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(a_ts.created), 86400) * 86400) as time,
  COUNT(a_ts.id) AS value,
  action as metric
FROM table_1 a_ts
LEFT JOIN table_2 ts ON ts.id = a_ts.monitor_id
GROUP BY time, action
ORDER BY time
LIMIT 10
```

Notice how the first column after the select does not have the single quotes around it. Let me know if you need any help, it's pretty easier to replicate.

- create two tables on bq related with a "foreign key" (there's no enforcement of constrain on bq but I'm sure you get my point). Make sure you have timestamp in that table
- setup latest grafana v9.2.6
- configure bq plugin
- try to query group by timestamp using the `$__timeGroup(a_ts.created, 1d)` syntax

**Comment by HaddadJoe** [comment]
@zoltanbedi here we go, https://github.com/grafana/google-bigquery-datasource/pull/155. Any expected timelines for cutting a new release? thanks for the help here!

**Comment by zoltanbedi** [comment]
@HaddadJoe I'll release this tomorrow once https://github.com/grafana/google-bigquery-datasource/pull/156 merged.

**Comment by zoltanbedi** [comment]
Sorry it took longer to release it but 1.2.3 is out with your PR. Thanks again @HaddadJoe.

**Comment by HaddadJoe** [comment]
tested works fine, feel free to close that issue. thanks for the collab here 💪
