### ISSUE TITLE
$__timeFrom() and $__timeTo() contain comparison operators

### ISSUE THREAD

**Issue by mjvankampen** [grafana/google-bigquery-datasource#158]
$__timeFrom() and $__timeTo() include <= and >= which makes it hard to use them in other contexts. For example I want to count distinct values in a range excluding values we already saw between one day before that start of the range and the start of the range.

**Comment by gabor** [comment]
hi @mjvankampen , in that case, you could use the `$__from` and `$__to` variables, they return the start and end timestamp as milliseconds. you can convert them to timestamps with `TIMESTAMP_MILLIS`, and then you have the freedom to use it as you need it, for example:
```sql
SELECT * FROM table1 WHERE
t >= TIMESTAMP_MILLIS($__from) AND t < TIMESTAMP_MILLIS($__to)
```

i hope this solves the problem.
i'll close the issue for now, but if it didn't help, please reply back and we'll reopen the issue. thanks!
