### ISSUE TITLE
BigQuery plugin - slow loading times + loop of errors with code status 500

### ISSUE THREAD

**Issue by joelmfonseca** [grafana/google-bigquery-datasource#160]
Hi, I am using a BigQuery datasource for one of my projects. I am facing an issue that is related to grafana and more precisely on the plugin for the BigQuery datasource (I guess).

When loading a dashboard that contains the BigQuery data source and every time I change de time window setting, refresh of the dashboards take ~10 +/- 5 seconds. Typically, the larger the time window (and therefore the number of points), the longer it takes to load properly. You can imagine the frustration of the end user. 

Here are the tracks I have already explored:

- Do a comparison between the cloud instance (GCE) versus locally => exact same behavior.
- Run the exact same query on BigQuery directly => I got results in < 1sec => query and data itself are OK.
- Inspect the grafana logs =>
<img width="1511" alt="Capture d’écran 2023-01-15 à 17 13 47" src="https://user-images.githubusercontent.com/18009243/212553042-6db3ed79-8ee6-4987-89cf-3e1afd22e923.png">

- Inspect the network logs from the console => 
<img width="1509" alt="Capture d’écran 2023-01-15 à 17 14 22" src="https://user-images.githubusercontent.com/18009243/212553056-0124061b-3c8c-473e-acd5-d5201964576c.png">

<img width="1512" alt="Capture d’écran 2023-01-15 à 17 17 11" src="https://user-images.githubusercontent.com/18009243/212553060-90c011e2-cd3e-46d5-9dfb-4380b6c6545e.png">

It might be related to this post as well; he got the same error but with another plugin/configuration: [Error 500 when update dashboard](https://community.grafana.com/t/error-500-when-update-dashboard/77291).

Thanks for your help! Happy to contribute if I have some additional insights!

**Comment by zoltanbedi** [comment]
Hi @joelmfonseca,

Do you have query caching enabled? Also can you please provide a way to reproduce this?

**Comment by gabor** [comment]
hi, as we got no response, we are closing the issue for now. if new info is provided, we can reopen it. thanks!
