### ISSUE TITLE
$__timeGroup with a big interval causes DIV(int64, float64)

### ISSUE THREAD

**Issue by Yooooomi** [grafana/google-bigquery-datasource#164]
Hello,

I have a global variable in my dashboard to customize the grouping interval in my requests. When this interval is big enough (14d+), the INT64 is transformed to a power of 10. Bigquery then thinks it is a FLOAT64 instead of an INT64.

```
$__timeGroup(messages.createdAt, $interval)
```

```
TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(messages.createdAt), 1.2096e+06) * 1.2096e+06)
```

Giving the following error:
`No matching signature for function DIV for argument types: INT64, FLOAT64. Supported signatures: DIV(INT64, INT64); DIV(NUMERIC, NUMERIC); DIV(BIGNUMERIC, BIGNUMERIC)`

Is it possible to write without the power of 10 or always cast the number to an INT64?
Many thanks.

**Comment by gabor** [comment]
hi @Yooooomi , sorry for the late response.
is the problem still actual?

if yes, could you descibe how that dashboard-variable is generated? it's not clear to me why it becomes a floating-point value ( i mean, why `1209600` suddenly becomes represented as `1.2096e+06`)?
thanks!

**Comment by zoltanbedi** [comment]
I'm going to close this issue now as we didn't got a response back. Let us know if we should reopen this issue.
