### ISSUE TITLE
query builder: automatically add $__timeFilter

### ISSUE THREAD

**Issue by pkoeltz** [grafana/google-bigquery-datasource#172]
# Expected Behavior
* Using **Time series** or **Stat** panels, I expect to use the calculations such as _Min, Max, Mean_ and see the correct values depending on the selected timeframe 
* Screenshot below is showing correct values in Legend over the last 3 hours: 
<img width="766" alt="image" src="https://github.com/grafana/google-bigquery-datasource/assets/112405499/e2d4035c-1944-477d-8abb-bc781ba319ce">

# Current Behavior
* Using **Time series** or **Stat** panels, the calculation values are in fact the one corresponding the whole series, as if the time filter were not applied for these calculation only. 
<img width="671" alt="image" src="https://github.com/grafana/google-bigquery-datasource/assets/112405499/6aa41c44-9925-47db-97cc-4e4ed71252af">

* This is becoming more clear in table view:
<img width="769" alt="image" src="https://github.com/grafana/google-bigquery-datasource/assets/112405499/4783c0b9-7038-4485-8af0-7f6ef7dff299">

* The table contains all the values, not only the last 3 hours

## Workaround
* As a workaround, I switched to the Code mode for the query, and added the timeFilter macro manually: 
<img width="145" alt="image" src="https://github.com/grafana/google-bigquery-datasource/assets/112405499/c5c9fb4e-f632-4c08-8622-3f914c60c640">

* The result is now working as expected: 
<img width="768" alt="image" src="https://github.com/grafana/google-bigquery-datasource/assets/112405499/73e1946f-64bf-46cd-889e-bed26be8d344">

<img width="767" alt="image" src="https://github.com/grafana/google-bigquery-datasource/assets/112405499/3db7fcf4-ea2f-40eb-a16f-7ced747687f6">

## Context
* Grafana version: 9.2.4
* BigQuery plugin version: 1.2.6

This might be linked (or duplicated) with https://github.com/grafana/google-bigquery-datasource/issues/137

**Comment by zoltanbedi** [comment]
hey @pkoeltz,
did you create your query with the query builder?

**Comment by pkoeltz** [comment]
Hi @zoltanbedi , thank you for looking into this. 

Yes the query was created with the query builder and resulted in this issue. Switching to code and adding the timeFilter macro in the query resolved the issue.

**Comment by Hipska** [comment]
timefilter should indeed be added by the query builder..

**Comment by zoltanbedi** [comment]
This is the same as https://github.com/grafana/google-bigquery-datasource/issues/139 so I'm going to close this.
