### ISSUE TITLE
Datasource is no longer able to communicate with a JWT

### ISSUE THREAD

**Issue by irving-derin-formlabs** [grafana/google-bigquery-datasource#176]
This was a weird situation and I haven't been able to recreate it yet. For some background I have a Grafana instance running on my computer. I use a Google Cloud Platform service account to access BigQuery and have been able to do so successfully for a few weeks now.

Earlier today while I was debugging a query in Grafana, I suddenly started to receive the following message:
```
error querying the database: Post "https://bigquery.googleapis.com/bigquery/v2/projects/my-amazing-project/queries?alt=json&prettyPrint=false": failed to retrieve google access token: oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_grant","error_description":"Invalid JWT Signature."}
``` 

After a few hours of debugging, as a sanity check I decided to create a new datasource with the same credentials. Unfortunately to add to the mystery, this worked fine. I then used the same exact JWT token file to update the original datasource but it continued to throw the same 400 errors.

**Comment by gabor** [comment]
hi @irving-derin-formlabs, thanks for submitting this issue! unfortunately, if it's not possible to reproduce it, there is not much we can do to improve the situation. for now we'll close this issue. if later you'll find the error happening again and you are able to trigger it, just respond here, and we'll reopen the issue. thanks!
