### ISSUE TITLE
Bug: Autocomplete does not kick in until you type in at least two characters

### ISSUE THREAD

**Issue by dprokop** [grafana/google-bigquery-datasource#18]
When starting from scratch, the autocomplete won't trigger until the user types in at least two characters into the raw query field:

https://user-images.githubusercontent.com/2376619/147106053-b1cede68-53f8-475d-9091-157893aba6d0.mov

Once the autocomplete triggers for the first time, it works just fine afterwards.

This bug started to appear when the custom language was introduced with this line: https://github.com/grafana/google-bigquery-datasource/commit/4386003cf7ce970d8280f2aee5846cccda68d922#diff-f711c358ee23cd55c48b49dad5ec8ae6ab32504caac666cc0ae24ce9677649e4R78

**Comment by gabor** [comment]
hi, i tested it with current grafana, and this seems to work correctly now: as soon as i press `S` in the raw query editor, i get autocomplete suggestions. closing the issue. if you think it's not fixed yet, please respond back and we can reopen the issue.
