### ISSUE TITLE
Inconsistent Preview of Values in Dashboard Variables in grafana v9.3.2

### ISSUE THREAD

**Issue by iamhritikkumar** [grafana/google-bigquery-datasource#182]
When executing a query to create Grafana dashboard variables using BigQuery datasource, the variable values are occasionally displayed correctly based on the query results. However, in most cases, the variable values are shown as "NONE" despite the query execution.

Google BigQuery Version: 1.2.7

<img width="823" alt="image" src="https://github.com/grafana/google-bigquery-datasource/assets/117714796/9843d3ad-1b57-4446-baa5-b7d9972634d4">

**Comment by zoltanbedi** [comment]
Hi @iamhritikkumar,

Can you please try to upgrade to 1.2.8? There was a fix for the variable queries.

**Comment by iamhritikkumar** [comment]
The issue has been resolved after updating it to version 1.2.8. Thank you for your assistance

**Comment by zoltanbedi** [comment]
Thanks for confirming @iamhritikkumar. 🙏
