### ISSUE TITLE
Add query processing data collection

### ISSUE THREAD

**Issue by baldm0mma** [grafana/google-bigquery-datasource#183]
From [this](https://raintank-corp.slack.com/archives/C023A30M3S7/p1686683922589859) conversation via Slack with @ljsmith93 

Start collecting how much data queries will process when they are run.

**Comment by scottlepp** [comment]
We will be able to capture some of these metrics once per plugin metrics are being scraped.

For other custom stuff like billed_bytes, I think we can just log it.  With proper log labeling we can run aggregation over the logs.

**Comment by szabalza** [comment]
Billing metrics were collected in some other way. There is no real demand for this feature at this point. We will reopen the ticket if there is a demand for it in the future
