### ISSUE TITLE
Swapping query order overwrites query

### ISSUE THREAD

**Issue by davkal** [grafana/google-bigquery-datasource#195]
1. Set up a dashboard panel with 2 big query queries
2. Drag the bottom one above the top one to change order
3. Click into the code editor of the bottom query, start typing
Result: the top query gets edited and overwritten.

**Comment by zoltanbedi** [comment]
I was not able to replicate this with Grafana v10.2.0-pre (050b9d9a856) and BQ version 1.3.1. Can you please give more details @davkal?

**Comment by gabor** [comment]
hi @davkal , as we did not get a response in a long time, we'll close the issue for now. we can always reopen it when we receive new info, thanks!
