### ISSUE TITLE
Plugin signature missing?

### ISSUE THREAD

**Issue by flori** [grafana/google-bigquery-datasource#199]
There seems to be a problem loading this plugin into Grafana v10.0.2 (b2bbe10fbc) because it is not signed:

```
logger=plugin.loader t=2023-07-26T23:35:24.95187026+02:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginID=doitintl-bigquery-datasource status=unsigned
```
Can you sign it and release a new version?

**Comment by zoltanbedi** [comment]
Hi @flori,
This is not the `doitintl-bigquery-datasource` but the `grafana-bigquery-datasource`.
