### ISSUE TITLE
Can't query multi-region datasets

### ISSUE THREAD

**Issue by carmitdanon** [grafana/google-bigquery-datasource#220]
When trying to query multi-region (EU or US) datasets, getting permission denied error
I am able to query single-region datasets using the same credentials 
Same behaviour for GCE/JWT authentication
Plugin version: 1.4.1, Grafana 10

**Comment by zoltanbedi** [comment]
I couldn't reproduce this problem. I have a dataset that is located in US and I was able to query it. If you can give clear repro steps that would help us understand the problem.
