### ISSUE TITLE
Support GOOGLE_APPLICATION_CREDENTIALS for authentification

### ISSUE THREAD

**Issue by owengo** [grafana/google-bigquery-datasource#221]
It seems that when "GCE Default Service Account" is used for auth, the GOOGLE_APPLICATION_CREDENTIALS env variable does not seem to be used by the server app, and it makes it impossible to use Workload Identity for auth in an AWS or Azure environment ( or any other environment supporting OIDC: Active Directory, Okta, K8s, .. ).
It would be a huge benefit for the ones who are reluctant to export private keys and it should be supported natively by the sdk.

**Comment by zoltanbedi** [comment]
Thanks for letting us know @owengo.
