### ISSUE TITLE
UI: hiding the project used for performing query jobs

### ISSUE THREAD

**Issue by nmdanny** [grafana/google-bigquery-datasource#230]
This is a bit of a niche feature request, and I have implemented in #227 (but perhaps not optimally), wonder if others have a similar use case.

We have the following scenario:

- Data to be queried is in project `Y`
- The query jobs should be made in project `Z`
- Grafana is running on a service account assigned to project `X` (or it is a user account, regardless, it is not related to `Y`/`Z`)

- Grafana's SA has `roles/bigquery.dataViewer`  on certain datasets/tables within project `Y` and also `resourcemanager.projects.get`,  `resourcemanager.projects.list` on project `Y`
- Grafana's SA has `roles/bigquery.jobUser` role on project `Z`

We would like the ability to hide project `Z` from the project-picker in the query builder UI, because it is an "internal" project that is only meant for billing & auditing purposes, it does not have any datasets that Grafana is permitted to query. 

Other than the hiding, this all works currently by configuring project `Z` as the `defaultProject` in the jsonData. I would also argue from a documentation purpose, it is not entirely obvious that this project is used for creating the query jobs, even when the user selects another project via the query builder (though it is desirable in this particular use-case)

**Comment by zoltanbedi** [comment]
This is completed in https://github.com/grafana/google-bigquery-datasource/pull/239
