### ISSUE TITLE
Query variable ignores __text and __value column names

### ISSUE THREAD

**Issue by urmuzov** [grafana/google-bigquery-datasource#248]
According to the general documentation on Query Variables, if you return two special column names `__text` and `__value`, they would be considered as display text and actual value of the variable.
https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#add-a-query-variable
No matter what I tried, seems like for BigQuery Query Variables these special names are ignored and only first column in results becomes display text and value.

Examples:
```sql
SELECT 'value1' AS __value, 'Display Text 1' AS __text
UNION ALL
SELECT 'value2' AS __value, 'Display Text 2' AS __text
```
and
```sql
SELECT 'Display Text 1' AS __text, 'value1' AS __value
UNION ALL
SELECT 'Display Text 2' AS __text, 'value2' AS __value
```
Not sure if this is a bug or a feature request.

**Comment by gabor** [comment]
hi @urmuzov , the documentation is not correct in this case (we will adjust it shortly), the names depend on the given datasource, for bigquery please use the names `text` and `value` (no double-underscore at the beginning), and it should work fine 👍 .

**Comment by jacobkassman** [comment]
@gabor
Two points of confusion I'd love to see at least cleared up in the documentation:
1. The [latest docs (3.4.1)](https://grafana.com/docs/plugins/grafana-bigquery-datasource/latest/template-variables/#list-values-with-a-display-name) still say `__text` and `__value`. I have found that doesn't work, it's `text` and `value` as you say here.
2. _Both need to be strings_, integers at least do not work (casting works, `CAST(my_value AS STRING)`)

Context: We couldn't get this mapping working for the a while, caused internal confusion (we were "waiting for a newer version with support" for a while). We had an integer `value` and a string `text`. Happened across this issue, and the combo of "cast to string" plus "no underscores" finally unblocked us.

Thank you!
