### ISSUE TITLE
"Expand Editor" button icon seems to have disappeared

### ISSUE THREAD

**Issue by shih-chris** [grafana/google-bigquery-datasource#260]
The "Expand Editor" button seems to have disappeared, but works once clicked.

**Grafana Cloud version:** Grafana v11.1.0-70724 (89f6845739)
**Google BigQuery plugin** (grafana-bigquery-datasource): version 1.2.7

_note:_ the bug still seems to occur on Google BigQuery plugin version 1.6.1

![image](https://github.com/grafana/google-bigquery-datasource/assets/14276197/7e391f6b-3270-4e5d-ab9f-7609976a1de0)

**Comment by gabor** [comment]
in grafana11.0.0 it is still correct.
but in grafana-main-branch it is not.

**Comment by gabor** [comment]
fixed in https://github.com/grafana/google-bigquery-datasource/pull/261
