### ISSUE TITLE
Add support for custom endpoint

### ISSUE THREAD

**Issue by vieux** [grafana/google-bigquery-datasource#267]
Hello  👋

I'm currently accessing bigquery through a custom proxy.

With the `bq` command-line tool, I use the `--api` flag to do this (see official documentation here: https://cloud.google.com/bigquery/docs/reference/bq-cli-reference)

I'd like to do the same via grafana.

See related PR: https://github.com/grafana/google-bigquery-datasource/pull/266

**Comment by ivanahuckova** [comment]
Closed by #266, will be part of the next release.
