### ISSUE TITLE
Not possible to create datasource in Grafana 8.2.7: Object(...) is not a function

### ISSUE THREAD

**Issue by dnnshssmnn** [grafana/google-bigquery-datasource#47]
Grafana: v8.2.7 oss docker image
Grafana BQ datasource: v0.1.10

Installing the datasource plugin works fine.
When trying to create new datasource, the following happens:
![grafik](https://user-images.githubusercontent.com/73958343/155352754-09bc60ec-5065-4955-9033-827967853f22.png)
This creates a datasource, but I can't do any settings. It's just showing the above when I click on the datasource.
I suspect it has to do with the fact that I run that Grafana instance in Docker, since I have another one running under Ubuntu where I don't face that issue (and also I can't spot any configuration differences). Hope you can replicate this, if you need more information let me know.

**Comment by dnnshssmnn** [comment]
Sorry, I missed the fact that I had Grafana 8.4.0 installed for the instance where it worked. So I just tried it with 8.2.7 on Ubuntu and it did not work either. So it has nothing to do with Docker.
I guess you will not fix compatibility with an older Grafana version, therefore I will close this issue.

**Comment by Elyahou** [comment]
Same issue here... This plugin is not compatible with grafana 8.2 ?

From the doc, it should be compatible with `Grafana 7.x || 8.x`
