### ISSUE TITLE
Selecting filter operation breaks query builder

### ISSUE THREAD

**Issue by benthorner** [grafana/google-bigquery-datasource#58]
If I try to change the filter operation from "==" to anything else, the value input (to the right of it) disappears and the select box for the filter operation still shows all the options, but won't let me select any of them.

| Before changing the operation | After changing it (unusable) |
| - | - |
| <img width="483" alt="Screenshot 2022-03-22 at 23 00 34" src="https://user-images.githubusercontent.com/9029009/159590446-3fab603d-a406-4c4d-9a12-f1284b5bb250.png"> | <img width="397" alt="Screenshot 2022-03-22 at 23 00 03" src="https://user-images.githubusercontent.com/9029009/159590445-69d336bc-bc13-412e-b684-4f9a32583afd.png"> |

I'm able to [manually write a query](https://github.com/grafana/google-bigquery-datasource#macros) for the same table and get data back, so I don't think there's anything wrong with the dataset / table. I can always manually write queries as a fallback - would be great if the builder worked though!

Metadata:

- Google BigQuery 0.1.11 installed on 22/03/2022, 22:47:40
- Grafana v8.4.3-54429

Tested on Chrome and Safari.

**Comment by dprokop** [comment]
@zoltanbedi do you mind having a look at this?

**Comment by zoltanbedi** [comment]
Not at all, I'll check this out asap.

**Comment by benthorner** [comment]
Amazing, thanks for fixing - look forward to using this data source!
