### ISSUE TITLE
Unexpected behavior with $__timeFilter() and casting

### ISSUE THREAD

**Issue by chs820** [grafana/google-bigquery-datasource#59]
## Description
Often in BigQuery, data is stored as dates, while Grafana requires timestamps for things like $__timeFilter(); however, it appears that at present, the following code is parsed incorrectly:

```where $__timeFilter(cast(date_stamp as timestamp))``` becomes
```where cast(date_stamp as timestamp >= '2017-04-01T04:00:00Z' AND cast(date_stamp as timestamp <= '2018-06-01T03:59:59Z')```

The closing ")" does not appear to be included.

**Screenshots**
![image](https://user-images.githubusercontent.com/14276197/159825740-ae0041b9-9d4c-4d81-9652-cbbb351a47e1.png)
![image](https://user-images.githubusercontent.com/14276197/159825775-2b1690bf-5276-4f14-8716-3f45b37a6375.png)

## Current workaround
My current workaround is to cast the date field to timestamp in a subquery or cte, which allows me to use the more typical pattern of `where $__timeFilter(time)`

**Comment by dprokop** [comment]
Yup, there is an issue in sqlds lib with the regex for capturing macros arguments. I'm on it @chs820.
