### ISSUE TITLE
Cannot update credentials

### ISSUE THREAD

**Issue by DanCech** [grafana/google-bigquery-datasource#65]
I am trying to update the datasource to use a new service account, but if I click "Reset token" then upload or paste a new token, then when I click "Save & test" nothing happens and the console logs a javascript error:
```
Uncaught TypeError: cyclic object value
    d fetch.ts:92
    r fetch.ts:9
    getFromFetchStream backend_srv.ts:189
    internalFetch backend_srv.ts:124
    F ResponseQueue.ts:30
    h RxJS
```

**Comment by dprokop** [comment]
Thanks @DanCech, on it very soon.

**Comment by dprokop** [comment]
Indeed, there's an issue here, I'm getting:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/2376619/161070082-886c8eeb-ab8e-4ca2-8274-b2f25a31ddc6.png">

**Comment by DanCech** [comment]
Thanks for the quick fix!
