### ISSUE TITLE
Feature Request: Enable cache options

### ISSUE THREAD

**Issue by pedrounes1** [grafana/google-bigquery-datasource#66]
Greetings!

This is not a issue, it's a feature request.

Is it possible to enable cache options?

Thanks in advance.

**Comment by dprokop** [comment]
@pedrounes1 query results are served from the BQ cache by default. Would you rather have an option to either disable/enable cached results of a query?

**Comment by pedrounes1** [comment]
@dprokop Thanks for your fast response.

No. I think that I did a bad / not enough explained request.

Every time that a user opens a dashboard, grafana do a request to BigQuery to fetch new data. So, if 100 users opens the same report at same time, grafana will do 100 requests to BigQuery, then store that data into each user session, right? This behaviour is good for keep everything updated, but on other hand raises our billing and can exceed  BQ simustaneous request limit (as, in fact, has occured in a stress test that we did).

Is there a way to cache that data in a way that only the first user trigger a request to BigQuery and all next accesses (within 5 mins or so) uses the same data? In another words, I want to replicate the behaviour from [this article]

**Comment by dprokop** [comment]
@pedrounes1 I think you have missed a link to an article you are referring to :)

**Comment by pedrounes1** [comment]
Fixed :)

**Comment by zoltanbedi** [comment]
Hi @pedrounes1,
The caching you linked is an enterprise only feature. You can enable it in this datasource as well on the datasource settings page at the Cache tab.
![Screenshot 2022-04-07 at 10 50 59](https://user-images.githubusercontent.com/13729989/162160406-639b35d8-42ba-416d-abac-d3e6957580ba.png)
