### ISSUE TITLE
Bug: Using variables cause error on query validation

### ISSUE THREAD

**Issue by Elyahou** [grafana/google-bigquery-datasource#71]
When using a variable in a query like the variable `${facility}` in this example:

```sql

SELECT
  $__timeGroup(created_at,$interval),
 avg(duration) as latency
FROM
  `table`
WHERE
  $__timeFilter(created_at)
  and name = 'foo'
  and facility in (${facility})
group by 1
order by 1

```
The query works, but it don't pass validation.
It cause a validation error on the query:

`Unrecognized name: my_facility at [x:x], invalidQuery`

I can see in the `validateQuery` http call, the request that is being validated do not contain quotes for the variable:

```sql
SELECT
  TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`created_at`), 60) * 60),
  avg(duration) as latency,
FROM
  `table`
WHERE
  created_at >= '2022-04-03T11:32:49Z' AND created_at <= '2022-04-03T14:32:49Z'
  and name = 'foo'
  and facility in (my_facility)
group by 1
order by 1
``` 

This line 
```sql
and facility in (my_facility)
```

should be (with quotes):
```sql
and facility in ('my_facility')
```

**Comment by dprokop** [comment]
@Elyahou - thanks for opening this issue, we'll take a look at this very soon.

**Comment by dprokop** [comment]
@Elyahou the fix is in main now and I'll release a new version tomorrow.
