### ISSUE TITLE
Feature Request: Allow data type selection in Query Builder

### ISSUE THREAD

**Issue by chs820** [grafana/google-bigquery-datasource#96]
## Problem Statement
One issue that we often run into with business data in BigQuery is that the "time" column is often of type date, rather than timestamp; however, for time-series plots Grafana requires timestamp data. 

## Possible implementation
Is it possible to allow users to, optionally, cast columns to specific datatypes in the "column" portion of the Query Builder (next to the aggregation selection)?

![image](https://user-images.githubusercontent.com/14276197/162507979-0db5cd98-ced8-4b51-9e21-aa304bbdf5c0.png)

**Comment by dprokop** [comment]
@chs820 would `Convert field type` transformation be a sufficient alternative for now? You can take a DATE field (which is returned as a string from BQ) and then convert it to a timestamp using `Convert field type` transformation:

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/2376619/162689500-fc6d759f-d5da-4de9-b024-c9a79fb14664.png">

Here's documentation about this transformation https://grafana.com/docs/grafana/latest/panels/reference-transformation-functions/#convert-field-type

**Comment by chs820** [comment]
Great call. Yeah, that works really well. I'm close this out
